[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "integration-llm"
version = "0.1.0"

dependencies = [
    "langchain-core",
]

[tool.setuptools.packages.find]
where = ["src"]