name: 'Docker Build and Push'
description: 'Builds a Docker image from a base image and pushes it to GHCR'
inputs:
  image_name:
    description: 'Docker image name to build (e.g. ollama/ollama:0.12.6)'
    required: true
  github_token:
    description: 'GitHub token for authentication'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create temporary Dockerfile
      shell: bash
      run: |
        echo "FROM ${{ inputs.image_name }}" > Dockerfile.tmp

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.tmp
        push: true
        load: true
        tags: ghcr.io/${{ github.repository }}/${{ inputs.image_name }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Docker images
      shell: bash
      run: |
        docker images

    - name: Tag Docker image
      shell: bash
      run: |
        docker tag ghcr.io/${{ github.repository }}/${{ inputs.image_name }} ${{ inputs.image_name }}
