[project]
name = "agents-core"
version = "0.1.0"

dependencies = [
    "pydantic==2.11.9",
]

[tool.pytest.ini_options]
pythonpath = ["src"] # Add src to python path for imports
testpaths = ["tests"] # Tell pytest where to find tests
