# .github/workflows/make.yml
name: Run Make

on: [ push ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print uname -m
        run: uname -m

      - name: Run make help
        run: make help

      - name: Run make
        run: make
