name: Test and Build

on: [ push ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: environment.yml
          activate-environment: agentic-knowledge-base

      - name: Install dependencies
        shell: bash -el {0}
        run: uv sync

      - name: Lint with Ruff
        shell: bash -el {0}
        run: uv run -- ruff check .

      - name: Check formatting with Ruff
        shell: bash -el {0}
        run: uv run -- ruff format --check .

      - name: which pytest
        shell: bash -el {0}
        run: |
          which pytest
          which uv

      - name: Run tests with pytest
        shell: bash -el {0}
        run: |
          conda env list
          uv run pytest
